### ISSUE TITLE
POST method doesn't work

### ISSUE THREAD

**Issue by ohmycloud** [lihaoyi/requests-scala#8]
when I execute `testPost` method, I get nothing:

```
  def testPost(): Unit = {
    val url = "https://jsonplaceholder.typicode.com/posts"

    val jsonInfo =
      """
        |{
        | "title": "foo",
        | "body": "bar",
        | "userId": "1"
        | }
      """.stripMargin

    val r = requests.post(url, data = jsonInfo )
    println(r.text())
  }
```

expect output:

```
{
    "title": "foo",
    "body": "bar",
    "userId": "1",
    "id": 101
}
```

dependency:

```
        <dependency>
            <groupId>com.lihaoyi</groupId>
            <artifactId>requests_2.11</artifactId>
            <version>0.1.2</version>
        </dependency>
```

**Comment by thomhickey** [comment]
Seems POST doesn't return a response body. I'd be happy to fork and PR this change if no one else has time?

**Comment by thomhickey** [comment]
Looking further this will happen for any response code 2xx other than 200 because Requester.stream() does:

`        val stream =
          if (connection.getResponseCode == 200) connection.getInputStream
          else connection.getErrorStream
`

The issue I'm seeing and perhaps others is that APIs often return the created resource on 201. In fact this is a best practice as per jsonapi.org: https://jsonapi.org/format/#crud-creating-responses ... I'm happy to change this to:

`        val stream =
          if (connection.getResponseCode.toString.startsWith("20")) connection.getInputStream
          else connection.getErrorStream
`

and PR it if agreed?
